-- V15__seed_mrs_meyers_rainwater_ingredients.sql
-- Seed / upsert GoodBuy ingredients + ingredient_signals
-- for Mrs. Meyer's Clean Day Laundry Detergent Rain Water
-- EAN: 00808124115576

BEGIN;

-- ─────────────────────────────────────────────
-- 1) INGREDIENTS: UPSERT 22 CANONICAL INGREDIENTS
-- ─────────────────────────────────────────────

INSERT INTO ingredients (
    canonical_key,
    display_name,
    summary,
    description,
    "function",
    concerns,
    safety_score,
    rating_letter,
    references_count,
    category,
    regulation_notes,
    is_active,
    func_use
) VALUES
    -- 1) Water
    ('water',
     'Water',
     'Primary solvent and diluent in laundry detergents.',
     'Water acts as the main carrier for surfactants and other ingredients in liquid detergents.',
     'Solvent',
     'No meaningful health concerns as used in consumer detergents.',
     99.00,  -- was 100.00; NUMERIC(4,2) max is 99.99
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Solvent'),

    -- 2) Laureth-7
    ('laureth-7',
     'Laureth-7',
     'Ethoxylated nonionic surfactant used for cleaning and foaming.',
     'Laureth-7 helps lift soils from fabrics and stabilize foam; it is widely used in household cleaners and personal care products.',
     'Nonionic surfactant',
     'Can cause mild skin and eye irritation at higher concentrations; ethoxylated surfactants may contain trace process impurities.',
     75.00,
     'B',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Nonionic surfactant'),

    -- 3) Lauryl Glucoside
    ('lauryl glucoside',
     'Lauryl Glucoside',
     'Mild nonionic surfactant derived from plant-based fatty alcohols and glucose.',
     'Lauryl glucoside is a sugar-based surfactant often used in “gentler” and plant-derived cleaning formulations.',
     'Nonionic surfactant',
     'Generally low irritation; occasional mild skin or eye irritation possible in sensitive users.',
     90.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Nonionic surfactant'),

    -- 4) Sodium Methyl 2-Sulfolaurate
    ('sodium methyl2-sulfolaurate',
     'Sodium Methyl 2-Sulfolaurate',
     'Anionic surfactant used in modern “sulfate-free” detergents.',
     'Sodium methyl 2-sulfolaurate is a newer anionic surfactant designed to be effective yet milder and more biodegradable than traditional sulfates.',
     'Anionic surfactant',
     'May cause mild skin and eye irritation in concentrate; typical laundry-use levels are considered low concern.',
     88.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Anionic surfactant'),

    -- 5) Fatty Acids (E570)
    ('fatty acids (e570)',
     'Fatty Acid',
     'Mixture of long-chain fatty acids used as surfactant co-components or builders.',
     'Food-grade long-chain fatty acids are commonly used in foods and detergents and are generally recognized as safe at normal use levels.',
     'Fatty acid / surfactant co-component',
     'Low overall concern; high concentrations of free fatty acids can be mildly irritating.',
     92.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Fatty acid / co-surfactant'),

    -- 6) C8–C18 and C18 Unsaturated Fatty Acids
    ('c8-c18 and c18 unsatd',
     'C8–C18 and C18 Unsaturated Fatty Acids',
     'Blend of medium- to long-chain fatty acids used as surfactant co-components or builders.',
     'These fatty acids act as auxiliaries in cleaning formulations and are similar in profile to other food-grade fatty acids.',
     'Fatty acid blend',
     'Low toxicity; prolonged skin contact with concentrates can be mildly irritating.',
     90.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Fatty acid blend'),

    -- 7) Fragrance
    ('fragrance',
     'Fragrance',
     'Mixture of aroma chemicals and essential oils to provide scent.',
     'Fragrance is a complex mixture that gives the product its scent; the exact composition is typically proprietary.',
     'Fragrance',
     'Fragrances are a common cause of allergic contact dermatitis, respiratory sensitivity, and headaches in sensitive individuals.',
     50.00,
     'C',
     0,
     'Cleaning ingredient',
     'Generic “fragrance” mixtures are a known source of contact allergens; several fragrance allergens are regulated in the EU.',
     TRUE,
     'Fragrance'),

    -- 8) Sodium Citrate (E331)
    ('sodium citrates (e331)',
     'Sodium Citrate',
     'pH buffer and water softening/builder salt.',
     'Sodium citrate is a citric acid salt used to buffer pH and bind metal ions, improving cleaning performance in hard water.',
     'Builder / buffering agent',
     'Widely used as a food additive; very low acute and chronic toxicity at detergent-use levels.',
     95.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Builder / buffering agent'),

    -- 9) Subtilisin Enzyme Blend
    ('subtilisin (protese) enzyme blend',
     'Subtilisin (Protease) Enzyme Blend',
     'Protease enzyme blend that breaks down protein stains.',
     'Subtilisin-type proteases help break down protein-based soils (e.g., blood, grass, food) on fabrics.',
     'Enzyme (protease)',
     'Enzymes can cause respiratory or skin sensitization in occupational settings; consumer risk is low when well-encapsulated and rinsed.',
     70.00,
     'B',
     0,
     'Cleaning ingredient',
     'Enzymes in detergents are regulated with occupational exposure limits and handling requirements.',
     TRUE,
     'Enzyme (protease)'),

    -- 10) Amylase Enzyme Blend
    ('amylase enzyme blend',
     'Amylase Enzyme Blend',
     'Enzyme blend that targets starch-based stains.',
     'Amylase enzymes help remove starch-heavy soils from fabrics in laundry detergents.',
     'Enzyme (amylase)',
     'Similar sensitization concerns as other detergent enzymes; consumer formulations are typically encapsulated or granulated.',
     70.00,
     'B',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Enzyme (amylase)'),

    -- 11) Lipase Enzyme Blend
    ('lipase enzyme blend',
     'Lipase Enzyme Blend',
     'Enzyme blend that targets fatty/oily stains.',
     'Lipase improves removal of fats and oils from fabrics.',
     'Enzyme (lipase)',
     'Enzymes can be respiratory sensitizers for workers; consumer risk is low when properly formulated.',
     70.00,
     'B',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Enzyme (lipase)'),

    -- 12) Mannanase Enzyme Blend
    ('mannanase enzyme blend',
     'Mannanase Enzyme Blend',
     'Enzyme blend that helps break down gums and plant-derived polysaccharides.',
     'Mannanase enhances removal of certain food and plant stains that contain galactomannans and related gums.',
     'Enzyme (mannanase)',
     'Same general enzyme sensitization concerns; typical in-wash exposure is low.',
     70.00,
     'B',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Enzyme (mannanase)'),

    -- 13) Tetrasodium Glutamate Diacetate (GLDA)
    ('tetrasodium glutamate diacetate',
     'Tetrasodium Glutamate Diacetate',
     'Biodegradable chelating agent used as an EDTA alternative.',
     'GLDA binds metal ions (like calcium and magnesium), boosting cleaning and stability; it has a favorable toxicity and biodegradability profile compared with older chelators.',
     'Chelating agent / builder',
     'Low acute toxicity and good biodegradability; overall considered a low-hazard chelator at detergent-use levels.',
     90.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Chelating agent / builder'),

    -- 14) Glycerin (Glycerol, E422)
    ('glycerol (e422)',
     'Glycerin',
     'Humectant and viscosity-modifying polyol.',
     'Glycerin is a simple three-carbon polyol widely used in foods, cosmetics, and cleaners.',
     'Humectant / solvent',
     'Very low toxicity; can be mildly irritating at high concentrations.',
     95.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Humectant / solvent'),

    -- 15) Citrus Aurantium Bergamia (Bergamot) Fruit Oil
    ('citrus aurantium bergamia (bergamot) fruit oil',
     'Citrus Aurantium Bergamia (Bergamot) Fruit Oil',
     'Essential oil that provides part of the fragrance profile.',
     'Bergamot oil is a citrus essential oil; some components can be phototoxic and allergenic.',
     'Fragrance / essential oil',
     'Can cause skin sensitization or phototoxic reactions, especially in leave-on or sun-exposed applications.',
     60.00,
     'C',
     0,
     'Cleaning ingredient',
     'Certain furocoumarins in bergamot oil are phototoxic and are restricted in cosmetics; rinse-off laundry use has lower exposure.',
     TRUE,
     'Fragrance / essential oil'),

    -- 16) Juniperus Virginiana (Cedarwood) Oil
    ('juniperus virginiana (cedarwood) oil',
     'Juniperus Virginiana (Cedarwood) Oil',
     'Essential oil contributing woody notes to the fragrance.',
     'Cedarwood oil provides a woody, balsamic fragrance note in the scent blend.',
     'Fragrance / essential oil',
     'May cause allergic contact dermatitis in sensitive individuals; overall hazard at rinse-off use levels is moderate to low.',
     75.00,
     'B',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Fragrance / essential oil'),

    -- 17) Calcium Chloride (E509)
    ('calcium chloride (e509)',
     'Calcium Chloride',
     'Inorganic salt used for stability or viscosity control.',
     'Calcium chloride is used in foods and industrial applications; in detergents it can help with stability and viscosity.',
     'Functional salt / stabilizer',
     'Concentrated solutions can be irritating; at low levels in laundry detergents, systemic risk is low.',
     80.00,
     'B',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Functional salt / stabilizer'),

    -- 18) Sodium Chloride (Salt)
    ('salt',
     'Sodium Chloride',
     'Common salt used as a functional additive (e.g., viscosity modifier).',
     'Sodium chloride is table salt; in detergents it is often used to adjust viscosity or crystallinity.',
     'Functional salt',
     'Very low toxicity; can cause mild irritation in high concentrations.',
     95.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Functional salt'),

    -- 19) Sodium Sulfate
    ('sodium sulfate',
     'Sodium Sulfate',
     'Inorganic salt used as a processing aid or filler.',
     'Sodium sulfate is a common inorganic salt used in detergents and other industrial processes.',
     'Functional salt / filler',
     'Low acute toxicity; dust can irritate eyes and respiratory tract in occupational settings.',
     85.00,
     'A',
     0,
     'Cleaning ingredient',
     NULL,
     TRUE,
     'Functional salt / filler'),

    -- 20) Potassium Hydroxide (E525)
    ('potassium hydroxide (e525)',
     'Potassium Hydroxide',
     'Strong alkali used to neutralize acids and form soaps.',
     'Potassium hydroxide is a caustic base; in detergents it is used in controlled amounts and is largely consumed in reactions.',
     'pH adjuster / saponification agent',
     'Corrosive in concentrated form with strong skin and eye damage potential; residual free base in finished formulas is tightly controlled.',
     40.00,
     'D',
     0,
     'Cleaning ingredient',
     'Strong base; subject to concentration and labeling requirements for corrosive products.',
     TRUE,
     'pH adjuster / saponification agent'),

    -- 21) Methylisothiazolinone (MIT)
    ('methylisothiazolinone',
     'Methylisothiazolinone',
     'Preservative used to prevent microbial growth.',
     'Methylisothiazolinone (MIT) is a powerful biocidal preservative used in many water-based products, including detergents and cleaners.',
     'Preservative / biocide',
     'Well-documented cause of allergic contact dermatitis; strongly sensitizing. Subject to strict concentration limits and bans in certain cosmetic uses.',
     20.00,
     'E',
     0,
     'Cleaning ingredient',
     'MIT is heavily restricted in EU cosmetics (especially leave-on) due to sensitization risk; still allowed at low levels in some rinse-off and non-cosmetic products.',
     TRUE,
     'Preservative / biocide'),

    -- 22) Benzisothiazolinone (BIT)
    ('benzisothiazolinone',
     'Benzisothiazolinone',
     'Preservative used for microbe control in detergents and cleaners.',
     'Benzisothiazolinone (BIT) is a preservative used primarily in industrial and household cleaning products.',
     'Preservative / biocide',
     'Associated with skin and respiratory sensitization; hazard depends on concentration and exposure pattern.',
     30.00,
     'D',
     0,
     'Cleaning ingredient',
     'Isothiazolinone preservatives, including BIT, are increasingly monitored and restricted in consumer products due to sensitization concerns.',
     TRUE,
     'Preservative / biocide')
ON CONFLICT (canonical_key) DO UPDATE
SET
    display_name     = COALESCE(ingredients.display_name, EXCLUDED.display_name),
    summary          = COALESCE(ingredients.summary, EXCLUDED.summary),
    description      = COALESCE(ingredients.description, EXCLUDED.description),
    "function"       = COALESCE(ingredients."function", EXCLUDED."function"),
    concerns         = COALESCE(ingredients.concerns, EXCLUDED.concerns),
    safety_score     = COALESCE(ingredients.safety_score, EXCLUDED.safety_score),
    rating_letter    = COALESCE(ingredients.rating_letter, EXCLUDED.rating_letter),
    references_count = COALESCE(ingredients.references_count, EXCLUDED.references_count),
    category         = COALESCE(ingredients.category, EXCLUDED.category),
    regulation_notes = COALESCE(ingredients.regulation_notes, EXCLUDED.regulation_notes),
    is_active        = ingredients.is_active OR EXCLUDED.is_active,
    func_use         = COALESCE(ingredients.func_use, EXCLUDED.func_use),
    updated_at       = NOW();

-- ─────────────────────────────────────────────
-- 2) INGREDIENT SIGNALS: UPSERT FLAGS (CONSERVATIVE)
--    - iarc_group, ewg_score are SMALLINT
--    - We explicitly cast to avoid type inference issues
-- ─────────────────────────────────────────────

INSERT INTO ingredient_signals (
    ingredient_id,
    iarc_group,
    prop65_listed,
    ewg_score,
    eu_prohibited,
    eu_restricted,
    pubchem_mutagen,
    pubchem_reproductive_toxin,
    epa_chronic_toxicity,
    skin_irritant
)
SELECT
    i.id,
    m.iarc_group,
    m.prop65_listed,
    m.ewg_score,
    m.eu_prohibited,
    m.eu_restricted,
    m.pubchem_mutagen,
    m.pubchem_reproductive_toxin,
    m.epa_chronic_toxicity,
    m.skin_irritant
FROM (
    VALUES
        -- canonical_key                                      iarc   prop65  ewg   eu_proh eu_rest mut   repro  epa_chronic skin_irrit
        ('water',                                         NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('laureth-7',                                     NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('lauryl glucoside',                              NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('sodium methyl2-sulfolaurate',                   NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('fatty acids (e570)',                            NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('c8-c18 and c18 unsatd',                         NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

        -- Fragrance: common sensitizer / irritant
        ('fragrance',                                     NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),

        ('sodium citrates (e331)',                        NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('subtilisin (protese) enzyme blend',             NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('amylase enzyme blend',                          NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('lipase enzyme blend',                           NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('mannanase enzyme blend',                        NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('tetrasodium glutamate diacetate',               NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('glycerol (e422)',                               NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('citrus aurantium bergamia (bergamot) fruit oil',NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('juniperus virginiana (cedarwood) oil',          NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('calcium chloride (e509)',                       NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('salt',                                          NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('sodium sulfate',                                NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
        ('potassium hydroxide (e525)',                    NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),

        -- Methylisothiazolinone & Benzisothiazolinone: strong sensitizers, EU-restricted
        ('methylisothiazolinone',                         NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE),
        ('benzisothiazolinone',                           NULL::SMALLINT, FALSE, NULL::SMALLINT, FALSE, TRUE,  FALSE, FALSE, FALSE, TRUE)
) AS m(
    canonical_key,
    iarc_group,
    prop65_listed,
    ewg_score,
    eu_prohibited,
    eu_restricted,
    pubchem_mutagen,
    pubchem_reproductive_toxin,
    epa_chronic_toxicity,
    skin_irritant
)
JOIN ingredients i ON i.canonical_key = m.canonical_key
ON CONFLICT (ingredient_id) DO UPDATE
SET
    iarc_group                 = COALESCE(ingredient_signals.iarc_group, EXCLUDED.iarc_group),
    prop65_listed              = ingredient_signals.prop65_listed OR EXCLUDED.prop65_listed,
    ewg_score                  = COALESCE(ingredient_signals.ewg_score, EXCLUDED.ewg_score),
    eu_prohibited              = ingredient_signals.eu_prohibited OR EXCLUDED.eu_prohibited,
    eu_restricted              = ingredient_signals.eu_restricted OR EXCLUDED.eu_restricted,
    pubchem_mutagen            = ingredient_signals.pubchem_mutagen OR EXCLUDED.pubchem_mutagen,
    pubchem_reproductive_toxin = ingredient_signals.pubchem_reproductive_toxin OR EXCLUDED.pubchem_reproductive_toxin,
    epa_chronic_toxicity       = ingredient_signals.epa_chronic_toxicity OR EXCLUDED.epa_chronic_toxicity,
    skin_irritant              = ingredient_signals.skin_irritant OR EXCLUDED.skin_irritant,
    updated_at                 = NOW();
