WITH seed(canonical_key, display_name, summary, description, concerns, category, regulation_notes, func_use, safety_score, rating_letter, references_count) AS (
    VALUES
        ('calcium carbonate', 'Calcium Carbonate', 'Mineral ingredient used as a calcium source and white color additive.', 'Calcium carbonate is used in supplements and foods as a calcium source, bulking agent, and white pigment.', 'Generally low concern in normal supplement use; excessive intake may cause stomach upset or contribute to mineral imbalance.', 'mineral', 'Commonly used in supplements and food additives.', 'calcium source, bulking agent', 90.00, 'A', 5),
        ('microcrystalline cellulose', 'Microcrystalline Cellulose', 'Purified cellulose used as a tablet binder and filler.', 'Microcrystalline cellulose helps hold tablets together and improve consistency in supplements and medicines.', 'Generally low concern; mainly used for tablet structure rather than nutrition.', 'binder', 'Widely used inactive ingredient in tablets and capsules.', 'binder, filler', 90.00, 'A', 5),
        ('ascorbic acid', 'Ascorbic Acid', 'Vitamin C ingredient used for nutrition and antioxidant support.', 'Ascorbic acid is vitamin C and is used in supplements and foods for nutritional and antioxidant purposes.', 'Generally low concern at normal intake; high doses may cause digestive upset in some people.', 'vitamin', 'Common nutrient ingredient in supplements and fortified foods.', 'vitamin c source, antioxidant', 90.00, 'A', 5),
        ('magnesium oxide', 'Magnesium Oxide', 'Magnesium source commonly used in supplements.', 'Magnesium oxide is a mineral ingredient used to supply magnesium and sometimes as a processing aid.', 'Generally low concern at normal supplement use; excess intake may cause diarrhea or stomach upset.', 'mineral', 'Common supplement mineral source.', 'magnesium source', 88.00, 'B', 5),
        ('ferrous fumarate', 'Ferrous Fumarate', 'Iron source commonly used in supplements.', 'Ferrous fumarate is an iron ingredient used in fortified foods and supplements.', 'Generally appropriate as an iron source; can cause constipation, nausea, or stomach upset in some people.', 'mineral', 'Common iron supplement form.', 'iron source', 85.00, 'B', 5),
        ('dl-alpha-tocopherol acetate', 'Vitamin E Acetate', 'Vitamin E ingredient used in supplements.', 'Vitamin E acetate is a stable form of vitamin E used in supplements and some topical products.', 'Generally low concern in oral supplement use at normal doses; product context matters for inhalation exposures.', 'vitamin', 'Common stable vitamin E form in supplements.', 'vitamin e source', 88.00, 'B', 5),
        ('niacinamide', 'Niacinamide', 'Vitamin B3 ingredient used in supplements and skin care.', 'Niacinamide is a form of vitamin B3 used in supplements and personal care products.', 'Generally low concern in standard supplement use; very high doses may cause side effects.', 'vitamin', 'Common supplemental vitamin B3 form.', 'vitamin b3 source', 88.00, 'B', 5),
        ('gelatin', 'Gelatin', 'Protein derived from animal collagen, often used in capsules and gummies.', 'Gelatin helps form capsules, gummies, and soft textures in supplements and foods.', 'Generally low concern for most people, but not suitable for some dietary restrictions and can matter for specific allergies.', 'gelling agent', 'Common capsule shell ingredient.', 'capsule shell, gelling agent', 85.00, 'B', 5),
        ('maltodextrin', 'Maltodextrin', 'Processed starch used as a filler or stabilizer.', 'Maltodextrin is commonly used to bulk, carry, or stabilize ingredients in foods and supplements.', 'Generally low concern in the small amounts used as an excipient, but it is a highly processed carbohydrate.', 'filler', 'Common excipient in supplements and packaged foods.', 'filler, carrier', 85.00, 'B', 5),
        ('silicon dioxide', 'Silicon Dioxide', 'Anti-caking ingredient that helps powders flow.', 'Silicon dioxide helps prevent clumping in powdered and tablet products.', 'Generally low concern in the small amounts used in supplements and foods.', 'anti-caking agent', 'Common anti-caking additive.', 'anti-caking agent', 90.00, 'A', 5),
        ('titanium dioxide', 'Titanium Dioxide', 'White pigment and opacifier used in some coatings.', 'Titanium dioxide is used to whiten or opacify capsules, tablets, and personal care products.', 'Context-dependent concern due to regulatory debate and route-of-exposure differences; often used as a coating color.', 'color additive', 'Use varies by jurisdiction and product category.', 'color additive, opacifier', 70.00, 'C', 5),
        ('magnesium stearate', 'Magnesium Stearate', 'Lubricant used in tablet manufacturing.', 'Magnesium stearate helps powders move through manufacturing equipment and keeps tablets from sticking.', 'Generally low concern in the small amounts used as a manufacturing aid.', 'processing aid', 'Widely used inactive ingredient in tablets.', 'lubricant', 88.00, 'B', 5),
        ('stearic acid', 'Stearic Acid', 'Fatty acid used as a lubricant or stabilizer.', 'Stearic acid is used in supplements and cosmetics to improve texture and manufacturing performance.', 'Generally low concern in typical supplement amounts.', 'processing aid', 'Common processing aid in tablets and capsules.', 'lubricant, stabilizer', 88.00, 'B', 5),
        ('hypromellose', 'Hypromellose', 'Cellulose-based coating and capsule ingredient.', 'Hypromellose is a plant-derived capsule shell and coating ingredient.', 'Generally low concern; mainly serves as a vegetarian capsule or coating material.', 'capsule ingredient', 'Common vegetarian capsule material.', 'capsule shell, coating', 90.00, 'A', 5),
        ('povidone', 'Povidone', 'Binder used in tablets and coatings.', 'Povidone helps ingredients bind together in tablets and coated products.', 'Generally low concern in normal pharmaceutical and supplement use.', 'binder', 'Common inactive tablet ingredient.', 'binder', 88.00, 'B', 5),
        ('crospovidone', 'Crospovidone', 'Disintegrant used to help tablets break apart.', 'Crospovidone helps tablets dissolve after swallowing.', 'Generally low concern; used to help tablets break apart properly.', 'disintegrant', 'Common inactive tablet ingredient.', 'disintegrant', 88.00, 'B', 5),
        ('croscarmellose sodium', 'Croscarmellose Sodium', 'Disintegrant used in tablets.', 'Croscarmellose sodium helps tablets break apart and dissolve more reliably.', 'Generally low concern in typical inactive-ingredient use.', 'disintegrant', 'Common inactive tablet ingredient.', 'disintegrant', 88.00, 'B', 5),
        ('polyethylene glycol', 'Polyethylene Glycol', 'Processing and coating ingredient.', 'Polyethylene glycol is used in coatings, capsules, and processing systems.', 'Context-dependent ingredient family; commonly used in coatings and processing, but some consumers prefer to limit it.', 'processing aid', 'Common excipient and coating aid.', 'coating aid, processing aid', 75.00, 'C', 5),
        ('soy lecithin', 'Soy Lecithin', 'Emulsifier derived from soy.', 'Soy lecithin helps oil- and water-based ingredients mix more evenly.', 'Generally low concern for most people, but soy-sensitive consumers may care about the source.', 'emulsifier', 'Common emulsifier in supplements and foods.', 'emulsifier', 88.00, 'B', 5),
        ('lecithin', 'Lecithin', 'Emulsifier used to keep ingredients blended.', 'Lecithin helps keep mixtures stable and evenly dispersed.', 'Generally low concern; source may matter for allergy-sensitive consumers.', 'emulsifier', 'Common emulsifier in supplements and foods.', 'emulsifier', 88.00, 'B', 5),
        ('red 40 lake', 'Red 40 Lake', 'Synthetic color additive.', 'Red 40 lake is a synthetic color additive used in coated tablets, gummies, and foods.', 'Synthetic color additive that some consumers choose to avoid.', 'color additive', 'Color additive use varies by product category and consumer preference.', 'color additive', 70.00, 'C', 5),
        ('yellow 6 lake', 'Yellow 6 Lake', 'Synthetic color additive.', 'Yellow 6 lake is a synthetic color additive used in tablets, gummies, and foods.', 'Synthetic color additive that some consumers choose to avoid.', 'color additive', 'Color additive use varies by product category and consumer preference.', 'color additive', 70.00, 'C', 5),
        ('blue 2 lake', 'Blue 2 Lake', 'Synthetic color additive.', 'Blue 2 lake is a synthetic color additive used in coated products and foods.', 'Synthetic color additive that some consumers choose to avoid.', 'color additive', 'Color additive use varies by product category and consumer preference.', 'color additive', 70.00, 'C', 5),
        ('dicalcium phosphate', 'Dicalcium Phosphate', 'Mineral compound used as a calcium source and tablet filler.', 'Dicalcium phosphate is commonly used in supplements as a source of calcium and as a tablet filler.', 'Generally low concern in supplement use.', 'mineral', 'Common supplement excipient and nutrient source.', 'calcium source, filler', 88.00, 'B', 5),
        ('biotin', 'Biotin', 'Vitamin B7 nutrient used in supplements.', 'Biotin is a B vitamin used in prenatal vitamins, hair supplements, and multivitamins.', 'Generally low concern in standard supplement use.', 'vitamin', 'Common vitamin ingredient.', 'vitamin b7 source', 90.00, 'A', 5),
        ('folic acid', 'Folic Acid', 'Synthetic folate used in supplements and fortified foods.', 'Folic acid is a common form of folate used in prenatal vitamins and fortified foods.', 'Generally low concern in standard supplement use and especially common in prenatal products.', 'vitamin', 'Common prenatal supplement ingredient.', 'folate source', 90.00, 'A', 5),
        ('calcium pantothenate', 'Calcium Pantothenate', 'Vitamin B5 ingredient used in supplements.', 'Calcium pantothenate is a stable form of vitamin B5 used in supplements and fortified foods.', 'Generally low concern in standard supplement use.', 'vitamin', 'Common supplemental vitamin B5 form.', 'vitamin b5 source', 90.00, 'A', 5),
        ('cyanocobalamin', 'Cyanocobalamin', 'Vitamin B12 ingredient used in supplements.', 'Cyanocobalamin is a common supplemental form of vitamin B12.', 'Generally low concern in standard supplement use.', 'vitamin', 'Common supplemental vitamin B12 form.', 'vitamin b12 source', 90.00, 'A', 5),
        ('pyridoxine hydrochloride', 'Pyridoxine Hydrochloride', 'Vitamin B6 ingredient used in supplements.', 'Pyridoxine hydrochloride is a common supplemental form of vitamin B6.', 'Generally low concern in standard supplement use.', 'vitamin', 'Common supplemental vitamin B6 form.', 'vitamin b6 source', 90.00, 'A', 5),
        ('riboflavin', 'Riboflavin', 'Vitamin B2 ingredient used in supplements.', 'Riboflavin is vitamin B2 and is commonly included in multivitamins and fortified foods.', 'Generally low concern in standard supplement use.', 'vitamin', 'Common supplemental vitamin B2 form.', 'vitamin b2 source', 90.00, 'A', 5),
        ('thiamine mononitrate', 'Thiamine Mononitrate', 'Vitamin B1 ingredient used in supplements.', 'Thiamine mononitrate is a common stable form of vitamin B1 used in supplements and fortified foods.', 'Generally low concern in standard supplement use.', 'vitamin', 'Common supplemental vitamin B1 form.', 'vitamin b1 source', 90.00, 'A', 5),
        ('zinc oxide', 'Zinc Oxide', 'Zinc source used in supplements and topical products.', 'Zinc oxide is used in supplements as a zinc source and in topical products as a protective mineral.', 'Generally low concern in oral supplement use at standard doses.', 'mineral', 'Common zinc ingredient.', 'zinc source', 88.00, 'B', 5),
        ('cupric sulfate', 'Cupric Sulfate', 'Copper source used in supplements.', 'Cupric sulfate is a copper compound used to supply copper in supplements and fortified products.', 'Generally low concern at standard supplement levels; excess copper intake can be harmful.', 'mineral', 'Common trace mineral ingredient.', 'copper source', 82.00, 'B', 5),
        ('manganese sulfate', 'Manganese Sulfate', 'Manganese source used in supplements.', 'Manganese sulfate is a trace mineral ingredient used to supply manganese in supplements.', 'Generally low concern at standard supplement levels; excess intake may not be appropriate for everyone.', 'mineral', 'Common trace mineral ingredient.', 'manganese source', 82.00, 'B', 5),
        ('potassium iodide', 'Potassium Iodide', 'Iodine source used in supplements.', 'Potassium iodide is used in supplements and fortified products as a source of iodine.', 'Generally low concern at standard supplement levels; iodine intake should still be appropriate for the person using it.', 'mineral', 'Common iodine source in supplements.', 'iodine source', 85.00, 'B', 5),
        ('sodium selenate', 'Sodium Selenate', 'Selenium source used in supplements.', 'Sodium selenate is a selenium compound used as a trace mineral source in supplements.', 'Generally low concern at standard supplement levels; selenium excess can be harmful.', 'mineral', 'Common trace mineral ingredient.', 'selenium source', 82.00, 'B', 5),
        ('chromium chloride', 'Chromium Chloride', 'Chromium source used in supplements.', 'Chromium chloride is a trace mineral compound used to supply chromium in supplements.', 'Generally low concern at standard supplement levels.', 'mineral', 'Common trace mineral ingredient.', 'chromium source', 82.00, 'B', 5),
        ('sodium molybdate', 'Sodium Molybdate', 'Molybdenum source used in supplements.', 'Sodium molybdate is a trace mineral ingredient used as a source of molybdenum in supplements.', 'Generally low concern at standard supplement levels.', 'mineral', 'Common trace mineral ingredient.', 'molybdenum source', 82.00, 'B', 5),
        ('cholecalciferol', 'Cholecalciferol', 'Vitamin D3 ingredient used in supplements.', 'Cholecalciferol is vitamin D3, a common form of vitamin D used in supplements.', 'Generally low concern at standard supplement levels.', 'vitamin', 'Common supplemental vitamin D form.', 'vitamin d source', 90.00, 'A', 5),
        ('retinyl acetate', 'Retinyl Acetate', 'Vitamin A ingredient used in supplements.', 'Retinyl acetate is a form of vitamin A used in supplements and fortified products.', 'Useful nutrient ingredient, but vitamin A dosing matters and excess intake can be a concern.', 'vitamin', 'Common supplemental vitamin A form.', 'vitamin a source', 80.00, 'B', 5),
        ('retinyl palmitate', 'Retinyl Palmitate', 'Vitamin A ingredient used in supplements.', 'Retinyl palmitate is a form of vitamin A used in supplements and fortified products.', 'Useful nutrient ingredient, but vitamin A dosing matters and excess intake can be a concern.', 'vitamin', 'Common supplemental vitamin A form.', 'vitamin a source', 80.00, 'B', 5),
        ('beta-carotene', 'Beta-Carotene', 'Carotenoid used as a provitamin A source and color ingredient.', 'Beta-carotene is a carotenoid used in supplements and foods as a source of provitamin A and as a pigment.', 'Generally low concern in typical dietary amounts; context can matter for heavy supplemental use.', 'vitamin', 'Common nutrient and pigment ingredient.', 'provitamin a source', 85.00, 'B', 5),
        ('modified food starch', 'Modified Food Starch', 'Processed starch used as a filler, stabilizer, or coating aid.', 'Modified food starch is used in supplements and foods to improve texture, stability, or coating performance.', 'Generally low concern in the small amounts used as an excipient.', 'processing aid', 'Common inactive ingredient.', 'filler, stabilizer', 85.00, 'B', 5),
        ('corn starch', 'Corn Starch', 'Starch ingredient used as a filler or processing aid.', 'Corn starch is used in tablets and capsules as a filler, binder, or processing aid.', 'Generally low concern in typical inactive-ingredient use.', 'filler', 'Common inactive ingredient.', 'filler, binder', 88.00, 'B', 5),
        ('sucrose', 'Sucrose', 'Sugar ingredient used as a sweetener or coating aid.', 'Sucrose is table sugar and may be used in coatings, chewables, and flavored supplements.', 'Generally low concern in small excipient amounts, though some consumers prefer to limit added sugars.', 'sweetener', 'Common food and supplement ingredient.', 'sweetener, coating aid', 82.00, 'B', 5),
        ('glucose syrup', 'Glucose Syrup', 'Sweetener and bulking ingredient used in gummies and chewables.', 'Glucose syrup is used in gummy and chewable products to provide sweetness and texture.', 'Generally low concern in small excipient amounts, though it is still an added sugar source.', 'sweetener', 'Common gummy and chewable base ingredient.', 'sweetener, bulking agent', 80.00, 'B', 5),
        ('carnauba wax', 'Carnauba Wax', 'Plant-derived coating and polishing agent.', 'Carnauba wax is used to coat and polish tablets, candies, and supplements.', 'Generally low concern in the small amounts used for coatings.', 'coating agent', 'Common polishing and coating aid.', 'coating, polishing agent', 88.00, 'B', 5)
),
upserted AS (
    INSERT INTO ingredients (
        canonical_key,
        display_name,
        summary,
        description,
        concerns,
        category,
        regulation_notes,
        func_use,
        safety_score,
        rating_letter,
        references_count,
        is_active
    )
    SELECT canonical_key,
           display_name,
           summary,
           description,
           concerns,
           category,
           regulation_notes,
           func_use,
           safety_score,
           rating_letter,
           references_count,
           TRUE
    FROM seed
    ON CONFLICT (canonical_key) DO UPDATE
    SET display_name = COALESCE(NULLIF(ingredients.display_name, ''), EXCLUDED.display_name),
        summary = COALESCE(NULLIF(ingredients.summary, ''), EXCLUDED.summary),
        description = COALESCE(NULLIF(ingredients.description, ''), EXCLUDED.description),
        concerns = COALESCE(NULLIF(ingredients.concerns, ''), EXCLUDED.concerns),
        category = COALESCE(NULLIF(ingredients.category, ''), EXCLUDED.category),
        regulation_notes = COALESCE(NULLIF(ingredients.regulation_notes, ''), EXCLUDED.regulation_notes),
        func_use = COALESCE(NULLIF(ingredients.func_use, ''), EXCLUDED.func_use),
        safety_score = COALESCE(ingredients.safety_score, EXCLUDED.safety_score),
        rating_letter = COALESCE(NULLIF(ingredients.rating_letter, ''), EXCLUDED.rating_letter),
        references_count = COALESCE(ingredients.references_count, EXCLUDED.references_count)
    RETURNING canonical_key
)
SELECT count(*) FROM upserted;

INSERT INTO ingredient_alias (ingredient_id, alias)
SELECT i.id, v.alias
FROM (
    VALUES
        ('calcium carbonate', 'calcium carbonate (e170)'),
        ('calcium carbonate', 'calcium carbonate (e170-i)'),
        ('calcium carbonate', 'calcium carbonate (ci pigment white 18, e170-i)'),
        ('microcrystalline cellulose', 'microcrystalline cellulose (e460-i)'),
        ('microcrystalline cellulose', 'mcc'),
        ('silicon dioxide', 'silicon dioxide (e551)'),
        ('titanium dioxide', 'titanium dioxide (ci pigment white 6, e171)'),
        ('titanium dioxide', 'ci pigment white 6'),
        ('titanium dioxide', 'e171'),
        ('niacinamide', 'niacinamide (vitamin b3)'),
        ('niacinamide', 'vitamin b3'),
        ('dl-alpha-tocopherol acetate', 'dl-alpha tocopherol acetate'),
        ('dl-alpha-tocopherol acetate', 'dl-alpha-tocopheryl acetate'),
        ('dl-alpha-tocopherol acetate', 'vitamin e'),
        ('ferrous fumarate', 'iron (as ferrous fumarate)'),
        ('calcium pantothenate', 'd-calcium pantothenate'),
        ('pyridoxine hydrochloride', 'vitamin b6'),
        ('riboflavin', 'vitamin b2'),
        ('thiamine mononitrate', 'vitamin b1'),
        ('cyanocobalamin', 'vitamin b12'),
        ('folic acid', 'folate'),
        ('cholecalciferol', 'vitamin d3'),
        ('retinyl acetate', 'vitamin a acetate'),
        ('retinyl palmitate', 'vitamin a palmitate'),
        ('biotin', 'vitamin b7'),
        ('potassium iodide', 'iodine'),
        ('sodium selenate', 'selenium'),
        ('chromium chloride', 'chromium'),
        ('sodium molybdate', 'molybdenum'),
        ('cupric sulfate', 'copper'),
        ('manganese sulfate', 'manganese'),
        ('zinc oxide', 'zinc'),
        ('dicalcium phosphate', 'dibasic calcium phosphate'),
        ('dicalcium phosphate', 'dcp'),
        ('polyethylene glycol', 'peg'),
        ('polyethylene glycol', 'peg 400'),
        ('polyethylene glycol', 'polyethylene glycol 400'),
        ('gelatin', 'softgel capsule'),
        ('gelatin', 'gelatin capsule'),
        ('hypromellose', 'vegetarian capsule'),
        ('hypromellose', 'hpmc'),
        ('corn starch', 'starch'),
        ('modified food starch', 'modified starch'),
        ('sucrose', 'sugar')
) AS v(canonical_key, alias)
JOIN ingredients i
  ON lower(i.canonical_key) = lower(v.canonical_key)
ON CONFLICT (ingredient_id, alias) DO NOTHING;
